"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createGist = createGist;
const axios_1 = __importDefault(require("axios"));
// 1. Get Token from Environment Variables (v2 style)
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
async function createGist(input) {
    var _a;
    const { filename, code } = input;
    if (!GITHUB_TOKEN) {
        console.error("❌ GITHUB_TOKEN is missing!");
        throw new Error("Server configuration error: Missing GitHub Token.");
    }
    try {
        const response = await axios_1.default.post('https://api.github.com/gists', {
            description: `Generated by ThinkFirst AI: ${filename}`,
            public: true,
            files: {
                [filename]: { content: code }
            }
        }, {
            headers: {
                Authorization: `token ${GITHUB_TOKEN}`,
                Accept: 'application/vnd.github.v3+json',
            }
        });
        return response.data.html_url;
    }
    catch (error) {
        console.error("Error posting to GitHub:", ((_a = error.response) === null || _a === void 0 ? void 0 : _a.data) || error.message);
        throw new Error("Failed to create Gist.");
    }
}
//# sourceMappingURL=gistService.js.map